
#AoA client-side configuration options
["General Settings"]
	#Set this to false to switch to a vertical layout for the HUD resources
	hudResourcesHorizontal = true
	#Set this to false to disable the small scrolling popups that appear when you gain xp in a skill
	showXpParticles = true
	#Set this to false to disable rotation of entities on trophy blocks.
	rotatingTrophies = true
	#The current theme for the main Advent of Ascension window.
	adventGuiTheme = "Default"
	#Choose a corner to have your resources indicators render in.
	#Allowed Values: Top_Right, Top_Left, Bottom_Right, Bottom_Left
	hudResourcesPosition = "Top_Right"
	#Set this to true to stop the skills and resources HUD elements shifting down when players have potion effects.
	disableHudPotionOffset = false
	#If multiple halos are available, which one would you prefer to have on?
	#Allowed Values: Donator, Super_Donator, Wiki_Editor
	personalHaloPreference = "Donator"
	#Set this to true to enable more detailed debugging.
	#If you don't mind your logs having a bit more info, or you are trying to figure out a bug or crash, this can be very helpful to have
	doVerboseDebugging = false
	#Set this to false to disable the message that welcomes you to Advent of Ascension when logging in
	showWelcomeMessage = true
	#Set this to false to limit your levels display to a max of level 100.
	#Levels above this are for prestige only and do not affect your gameplay
	showVanityLevels = true
	#Setting this to false allows the game to continue running as normal while the Advent of Ascension GUI is open.
	adventGuiPausesGame = true
	#Set this to false to disable third party and vanilla entities from showing in the bestiary
	thirdPartyBestiary = true
	#Set this to false to use chat messages for mod feedback instead of toasts
	useToasts = true
	#Set this to false to hide player halos for those that have them
	showPlayerHalos = true

#Just for fun :)
["Fun Options"]
	#Set this to true for Chargers. All the chargers
	alwaysChargers = false
	#Set this to true to enable party deaths
	partyDeaths = false

