
#Wires
[wires]
	#Connector max input in FE/t (Energy transfer).
	#Range: > 0
	connector_max_input = 2048
	#Loss per block in gold wire (Not implemented, currently no loss).
	#Range: 0.0 ~ 0.5
	gold_wire_loss = 0.005
	#Connector internal capacity in FE.
	#Range: > 0
	connector_capacity = 4096
	#Loss per block in copper wire (Not implemented, currently no loss).
	#Range: 0.0 ~ 0.5
	copper_wire_loss = 0.02
	#Connector max output in FE/t (Energy transfer).
	#Range: > 0
	connector_max_output = 2048

#General Settings
[general]
	#Baseline stress factor for the Alternator and Electric Motor.
	#Range: > 0
	generator_stress = 4096
	#Forge Energy conversion rate (in FE/t at max RPM).
	#Range: > 0
	fe_conversion = 80

#Charger
[charger]
	#Charger max input in FE/t (Energy transfer).
	#Range: > 0
	charger_max_input = 8192
	#Charger charge rate in FE/t.
	#Range: > 0
	charger_charge_rate = 8192
	#Charger internal capacity in FE.
	#Range: > 0
	charger_capacity = 32000

#Electric Motor
[electric_motor]
	#Electric Motor internal capacity in FE.
	#Range: > 0
	motor_capacity = 4096
	#Electric Motor minimum required energy consumption in FE/t.
	#Range: > 0
	motor_min_consumption = 10
	#Electric Motor max input in FE (Energy transfer not consumption).
	#Range: > 0
	motor_max_input = 4096
	#Electric Motor min/max RPM.
	#Range: 1 ~ 256
	motor_rpm_range = 256

#Heater
[heater]
	#Enable Induction Heater when attached to a Furnace Engine.
	heater_furnace_engine_enable = false
	#Induction Heater internal capacity in FE.
	#Range: > 0
	heater_capacity = 2048
	#Induction Heater max input in FE (Energy transfer not consumption).
	#Range: > 0
	heater_max_input = 2048
	#Induction Heater normal consumption rate in FE/t.
	#Range: > 0
	heater_normal_consumption = 16
	#Induction Heater when attached to a Furnace Engine consumption rate in FE/t.
	#Range: > 0
	heater_furnace_engine_consumption = 400

#Alternator
[alternator]
	#Alternator efficiency relative to base conversion rate.
	#Range: 0.01 ~ 1.0
	generator_efficiency = 0.75
	#Alternator internal capacity in FE.
	#Range: > 0
	generator_capacity = 4096
	#Alternator max input in FE (Energy transfer not generation).
	#Range: > 0
	generator_max_output = 4096

#Accumulator
[accumulator]
	#Accumulator internal capacity in FE.
	#Range: > 0
	accumulator_capacity = 4196000
	#Accumulator max output in FE/t (Energy transfer).
	#Range: > 0
	accumulator_max_output = 8192
	#Accumulator max input in FE/t (Energy transfer).
	#Range: > 0
	accumulator_max_input = 8192

#Rolling Mill
[rolling_mill]
	#Rolling Mill duration in ticks.
	#Range: > 0
	rolling_mill_processing_duration = 100
	#Rolling Mill base stress impact.
	#Range: 0 ~ 1024
	rolling_mill_stress = 16

#Misc
[misc]
	#Diamond Grit Sandpaper durability (number of uses).
	#Range: > 3
	diamond_grit_sandpaper_uses = 1024

